"""initial governed research schema

Revision ID: 08bc4fd6c08b
Revises:
Create Date: 2026-08-01 14:48:59.782109
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "08bc4fd6c08b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.String(length=96), nullable=False),
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("uri", sa.String(length=128), nullable=False),
        sa.Column("media_type", sa.String(length=256), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("restricted", sa.Boolean(), nullable=False),
        sa.Column("raw_data", sa.Boolean(), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("digest"),
        sa.UniqueConstraint("uri"),
    )
    op.create_table(
        "competencies",
        sa.Column("competency_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parent_competency_id", sa.String(length=128), nullable=True),
        sa.Column("prerequisite_ids", sa.JSON(), nullable=False),
        sa.Column("grader_requirements", sa.JSON(), nullable=False),
        sa.Column("teacher_modes", sa.JSON(), nullable=False),
        sa.Column("difficulty_calibration", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_competency_id"], ["competencies.competency_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("competency_id"),
    )
    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=96), nullable=False),
        sa.Column("parent_state_id", sa.String(length=96), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("design", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "lesson_versions",
        sa.Column("lesson_version_id", sa.String(length=128), nullable=False),
        sa.Column("lesson_id", sa.String(length=96), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.String(length=128), nullable=False),
        sa.Column("error_class", sa.String(length=128), nullable=False),
        sa.Column("state_lineage_id", sa.String(length=128), nullable=False),
        sa.Column("branch_id", sa.String(length=96), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("general_rule", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("successful_transfer_count", sa.Integer(), nullable=False),
        sa.Column("failed_transfer_count", sa.Integer(), nullable=False),
        sa.Column("harmful_retrieval_count", sa.Integer(), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("lesson_version_id"),
        sa.UniqueConstraint("lesson_id", "version", name="uq_lesson_version"),
    )
    with op.batch_alter_table("lesson_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lesson_retrieval", ["competency_id", "error_class", "status"], unique=False
        )

    op.create_table(
        "memory_snapshots",
        sa.Column("snapshot_id", sa.String(length=96), nullable=False),
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("state_lineage_id", sa.String(length=128), nullable=False),
        sa.Column("branch_id", sa.String(length=96), nullable=False),
        sa.Column("active_lesson_versions", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_table(
        "provenance_heads",
        sa.Column("stream_id", sa.String(length=128), nullable=False),
        sa.Column("last_position", sa.Integer(), nullable=False),
        sa.Column("chain_hash", sa.String(length=71), nullable=False),
        sa.PrimaryKeyConstraint("stream_id"),
    )
    op.create_table(
        "retrieval_decisions",
        sa.Column("retrieval_id", sa.String(length=96), nullable=False),
        sa.Column("state_id", sa.String(length=96), nullable=False),
        sa.Column("branch_id", sa.String(length=96), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("candidate_lesson_ids", sa.JSON(), nullable=False),
        sa.Column("retrieved_lesson_ids", sa.JSON(), nullable=False),
        sa.Column("rejected", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("retrieval_id"),
    )
    op.create_table(
        "review_queue",
        sa.Column("review_id", sa.String(length=96), nullable=False),
        sa.Column("review_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=192), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=96), nullable=False),
        sa.Column("episode_id", sa.String(length=96), nullable=True),
        sa.Column("student_id", sa.String(length=128), nullable=True),
        sa.Column("active_student_id", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("retry_budget", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_token", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("active_student_id", name="uq_run_active_student"),
        sa.UniqueConstraint("episode_id"),
        sa.UniqueConstraint("lease_token"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index("ix_run_claim", ["state", "lease_expires_at"], unique=False)
        batch_op.create_index("ix_run_student", ["student_id", "created_at"], unique=False)

    op.create_table(
        "students",
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_state_id", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("student_id"),
    )
    op.create_table(
        "workers",
        sa.Column("worker_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_run_id", sa.String(length=96), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "artifact_references",
        sa.Column("reference_id", sa.String(length=96), nullable=False),
        sa.Column("owner_type", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=192), nullable=False),
        sa.Column("artifact_id", sa.String(length=96), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("reference_id"),
        sa.UniqueConstraint("owner_type", "owner_id", "artifact_id", name="uq_artifact_ref"),
    )
    op.create_table(
        "experiment_blocks",
        sa.Column("block_id", sa.String(length=96), nullable=False),
        sa.Column("experiment_id", sa.String(length=96), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("assignment", sa.JSON(), nullable=False),
        sa.Column("outcomes", sa.JSON(), nullable=True),
        sa.Column("contamination_detected", sa.Boolean(), nullable=False),
        sa.Column("infrastructure_failure", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.experiment_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("block_id"),
        sa.UniqueConstraint("experiment_id", "block_index"),
    )
    op.create_table(
        "external_calls",
        sa.Column("request_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=96), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=71), nullable=False),
        sa.Column("request_artifact_id", sa.String(length=96), nullable=False),
        sa.Column("response_artifact_id", sa.String(length=96), nullable=True),
        sa.Column("provider_response_id", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "provenance_events",
        sa.Column("event_id", sa.String(length=96), nullable=False),
        sa.Column("stream_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_event_ids", sa.JSON(), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("state_lineage_id", sa.String(length=96), nullable=True),
        sa.Column("episode_id", sa.String(length=96), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=71), nullable=False),
        sa.Column("previous_chain_hash", sa.String(length=71), nullable=False),
        sa.Column("chain_hash", sa.String(length=71), nullable=False),
        sa.Column("code_revision", sa.String(length=128), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["stream_id"], ["provenance_heads.stream_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("chain_hash"),
        sa.UniqueConstraint("stream_id", "position", name="uq_provenance_stream_position"),
    )
    with op.batch_alter_table("provenance_events", schema=None) as batch_op:
        batch_op.create_index("ix_provenance_episode", ["episode_id"], unique=False)
        batch_op.create_index("ix_provenance_state", ["state_lineage_id"], unique=False)

    op.create_table(
        "run_transitions",
        sa.Column("transition_id", sa.String(length=96), nullable=False),
        sa.Column("run_id", sa.String(length=96), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(length=64), nullable=False),
        sa.Column("to_state", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("transition_id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_transition_sequence"),
    )
    op.create_table(
        "student_states",
        sa.Column("state_id", sa.String(length=96), nullable=False),
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("runtime_id", sa.String(length=256), nullable=False),
        sa.Column("parent_state_id", sa.String(length=96), nullable=True),
        sa.Column("branch_id", sa.String(length=96), nullable=False),
        sa.Column("compacted_working_state", sa.JSON(), nullable=False),
        sa.Column("lesson_memory_refs", sa.JSON(), nullable=False),
        sa.Column("unresolved_hypotheses", sa.JSON(), nullable=False),
        sa.Column("competency_estimates", sa.JSON(), nullable=False),
        sa.Column("active_experiment_id", sa.String(length=96), nullable=True),
        sa.Column("state_hash", sa.String(length=71), nullable=False),
        sa.Column("creation_reason", sa.Text(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_state_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.student_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("state_id"),
        sa.UniqueConstraint("student_id", "state_hash", name="uq_student_state_hash"),
    )
    with op.batch_alter_table("student_states", schema=None) as batch_op:
        batch_op.create_index(
            "ix_state_branch", ["student_id", "branch_id", "created_at"], unique=False
        )

    op.create_table(
        "template_families",
        sa.Column("template_family_id", sa.String(length=160), nullable=False),
        sa.Column("competency_id", sa.String(length=128), nullable=False),
        sa.Column("visibility_class", sa.String(length=24), nullable=False),
        sa.Column("generator_version", sa.String(length=128), nullable=False),
        sa.Column("lineage_digest", sa.String(length=71), nullable=False),
        sa.Column("contaminated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "visibility_class IN ('training', 'evaluation', 'sealed')",
            name="ck_template_visibility",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.competency_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("template_family_id"),
        sa.UniqueConstraint("lineage_digest"),
        sa.UniqueConstraint("template_family_id", "visibility_class"),
    )
    op.create_table(
        "instance_groups",
        sa.Column("instance_group_id", sa.String(length=160), nullable=False),
        sa.Column("template_family_id", sa.String(length=160), nullable=False),
        sa.Column("visibility_class", sa.String(length=24), nullable=False),
        sa.Column("generation_seed", sa.Integer(), nullable=False),
        sa.Column("sibling_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_family_id", "visibility_class"],
            ["template_families.template_family_id", "template_families.visibility_class"],
            name="fk_instance_group_family_visibility",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("instance_group_id"),
        sa.UniqueConstraint(
            "instance_group_id",
            "template_family_id",
            "visibility_class",
            name="uq_instance_group_lineage",
        ),
    )
    op.create_table(
        "state_forks",
        sa.Column("fork_id", sa.String(length=96), nullable=False),
        sa.Column("parent_state_id", sa.String(length=96), nullable=False),
        sa.Column("treatment_state_id", sa.String(length=96), nullable=False),
        sa.Column("control_state_id", sa.String(length=96), nullable=False),
        sa.Column("treatment_branch_id", sa.String(length=96), nullable=False),
        sa.Column("control_branch_id", sa.String(length=96), nullable=False),
        sa.Column("intervention", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "treatment_branch_id <> control_branch_id", name="ck_fork_distinct_branches"
        ),
        sa.CheckConstraint(
            "treatment_state_id <> control_state_id", name="ck_fork_distinct_states"
        ),
        sa.ForeignKeyConstraint(
            ["control_state_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_state_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["treatment_state_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("fork_id"),
        sa.UniqueConstraint("control_state_id"),
        sa.UniqueConstraint("treatment_state_id"),
    )
    op.create_table(
        "corpus_items",
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("competency_id", sa.String(length=128), nullable=False),
        sa.Column("template_family_id", sa.String(length=160), nullable=False),
        sa.Column("instance_group_id", sa.String(length=160), nullable=False),
        sa.Column("visibility_class", sa.String(length=24), nullable=False),
        sa.Column("generation_seed", sa.Integer(), nullable=False),
        sa.Column("generator_version", sa.String(length=128), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.JSON(), nullable=True),
        sa.Column("verifier_spec", sa.JSON(), nullable=False),
        sa.Column("pool", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("license", sa.String(length=128), nullable=False),
        sa.Column("contamination_scope", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_token", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_attempt", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retirement_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(pool = 'quarantine') OR (pool = 'curriculum' AND visibility_class = 'training') OR (pool = 'rotating_shadow' AND visibility_class = 'evaluation') OR (pool = 'sealed_anchor' AND visibility_class = 'sealed')",
            name="ck_item_pool_visibility",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'leased', 'retired', 'quarantined')", name="ck_item_status"
        ),
        sa.CheckConstraint("difficulty >= 0 AND difficulty <= 1", name="ck_item_difficulty"),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.competency_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["instance_group_id", "template_family_id", "visibility_class"],
            [
                "instance_groups.instance_group_id",
                "instance_groups.template_family_id",
                "instance_groups.visibility_class",
            ],
            name="fk_item_instance_lineage",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("item_id"),
    )
    with op.batch_alter_table("corpus_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_corpus_lease", ["pool", "status", "lease_expires_at"], unique=False
        )

    op.create_table(
        "episodes",
        sa.Column("episode_id", sa.String(length=96), nullable=False),
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("state_before_id", sa.String(length=96), nullable=False),
        sa.Column("state_after_id", sa.String(length=96), nullable=True),
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["corpus_items.item_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["state_after_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["state_before_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.student_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("episode_id"),
    )
    op.create_table(
        "exposures",
        sa.Column("exposure_id", sa.String(length=96), nullable=False),
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("state_id", sa.String(length=96), nullable=False),
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("template_family_id", sa.String(length=160), nullable=False),
        sa.Column("instance_group_id", sa.String(length=160), nullable=False),
        sa.Column("exposure_type", sa.String(length=32), nullable=False),
        sa.Column("prompt_exposed", sa.Boolean(), nullable=False),
        sa.Column("answer_exposed", sa.Boolean(), nullable=False),
        sa.Column("critique_exposed", sa.Boolean(), nullable=False),
        sa.Column("repair_exposed", sa.Boolean(), nullable=False),
        sa.Column("metadata_exposed", sa.Boolean(), nullable=False),
        sa.Column("episode_id", sa.String(length=96), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["corpus_items.item_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("exposure_id"),
        sa.UniqueConstraint(
            "student_id",
            "state_id",
            "item_id",
            "exposure_type",
            "episode_id",
            name="uq_exposure_idempotency",
        ),
    )
    with op.batch_alter_table("exposures", schema=None) as batch_op:
        batch_op.create_index(
            "ix_exposure_family", ["student_id", "template_family_id"], unique=False
        )

    op.create_table(
        "attempts",
        sa.Column("attempt_id", sa.String(length=96), nullable=False),
        sa.Column("episode_id", sa.String(length=96), nullable=False),
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("state_before_id", sa.String(length=96), nullable=False),
        sa.Column("state_after_id", sa.String(length=96), nullable=True),
        sa.Column("request_id", sa.String(length=160), nullable=False),
        sa.Column("response_id", sa.String(length=256), nullable=True),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("runtime_id", sa.String(length=256), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.episode_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["corpus_items.item_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["state_after_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["state_before_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint("request_id", name="uq_attempt_request"),
    )
    op.create_table(
        "transfer_trials",
        sa.Column("transfer_trial_id", sa.String(length=96), nullable=False),
        sa.Column("episode_id", sa.String(length=96), nullable=False),
        sa.Column("experiment_id", sa.String(length=96), nullable=True),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.episode_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("transfer_trial_id"),
    )
    op.create_table(
        "grades",
        sa.Column("grade_id", sa.String(length=96), nullable=False),
        sa.Column("attempt_id", sa.String(length=96), nullable=False),
        sa.Column("deterministic", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=48), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.attempt_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("grade_id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_table(
        "teacher_interventions",
        sa.Column("intervention_id", sa.String(length=96), nullable=False),
        sa.Column("episode_id", sa.String(length=96), nullable=False),
        sa.Column("attempt_id", sa.String(length=96), nullable=False),
        sa.Column("request_id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.attempt_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.episode_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("intervention_id"),
        sa.UniqueConstraint("request_id", name="uq_teacher_request"),
    )
    op.create_table(
        "revisions",
        sa.Column("revision_id", sa.String(length=96), nullable=False),
        sa.Column("original_attempt_id", sa.String(length=96), nullable=False),
        sa.Column("intervention_id", sa.String(length=96), nullable=False),
        sa.Column("revised_attempt_id", sa.String(length=96), nullable=False),
        sa.Column("revised_grade_id", sa.String(length=96), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["intervention_id"], ["teacher_interventions.intervention_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["original_attempt_id"], ["attempts.attempt_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["revised_attempt_id"], ["attempts.attempt_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["revised_grade_id"], ["grades.grade_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("revision_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revisions")
    op.drop_table("teacher_interventions")
    op.drop_table("grades")
    op.drop_table("transfer_trials")
    op.drop_table("attempts")
    with op.batch_alter_table("exposures", schema=None) as batch_op:
        batch_op.drop_index("ix_exposure_family")

    op.drop_table("exposures")
    op.drop_table("episodes")
    with op.batch_alter_table("corpus_items", schema=None) as batch_op:
        batch_op.drop_index("ix_corpus_lease")

    op.drop_table("corpus_items")
    op.drop_table("state_forks")
    op.drop_table("instance_groups")
    op.drop_table("template_families")
    with op.batch_alter_table("student_states", schema=None) as batch_op:
        batch_op.drop_index("ix_state_branch")

    op.drop_table("student_states")
    op.drop_table("run_transitions")
    with op.batch_alter_table("provenance_events", schema=None) as batch_op:
        batch_op.drop_index("ix_provenance_state")
        batch_op.drop_index("ix_provenance_episode")

    op.drop_table("provenance_events")
    op.drop_table("external_calls")
    op.drop_table("experiment_blocks")
    op.drop_table("artifact_references")
    op.drop_table("workers")
    op.drop_table("students")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_run_claim")
        batch_op.drop_index("ix_run_student")

    op.drop_table("runs")
    op.drop_table("review_queue")
    op.drop_table("retrieval_decisions")
    op.drop_table("provenance_heads")
    op.drop_table("memory_snapshots")
    with op.batch_alter_table("lesson_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_lesson_retrieval")

    op.drop_table("lesson_versions")
    op.drop_table("experiments")
    op.drop_table("competencies")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
