"""add reward study and checkpoint governance

Revision ID: 0ace28c76900
Revises: 4a9c7d8e2f10
Create Date: 2026-08-01 21:20:26.333985
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0ace28c76900"
down_revision: str | Sequence[str] | None = "4a9c7d8e2f10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkpoint_promotion_policies",
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("policy_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("policy_id", "version"),
        sa.UniqueConstraint("policy_digest"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=256), nullable=True),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("tokenizer_id", sa.String(length=256), nullable=False),
        sa.Column("model_digest", sa.String(length=71), nullable=False),
        sa.Column("tokenizer_digest", sa.String(length=71), nullable=False),
        sa.Column("training_bundle_manifest_digest", sa.String(length=71), nullable=True),
        sa.Column("manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate', 'evaluating', 'promoted', 'rejected', 'quarantined', 'revoked')",
            name="ck_checkpoint_status",
        ),
        sa.CheckConstraint(
            "parent_checkpoint_id IS NULL OR parent_checkpoint_id <> checkpoint_id",
            name="ck_checkpoint_parent_distinct",
        ),
        sa.ForeignKeyConstraint(
            ["parent_checkpoint_id"], ["checkpoints.checkpoint_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("checkpoint_id"),
        sa.UniqueConstraint("manifest_digest"),
        sa.UniqueConstraint("model_digest"),
    )
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            "ix_checkpoint_model_status", ["model_id", "status", "created_at"], unique=False
        )

    op.create_table(
        "evaluation_suites",
        sa.Column("manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("sealed", sa.Boolean(), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("manifest_digest"),
        sa.UniqueConstraint("suite_id", "version", name="uq_evaluation_suite_version"),
    )
    op.create_table(
        "reward_policies",
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("policy_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("policy_id", "version"),
        sa.UniqueConstraint("policy_digest"),
    )
    op.create_table(
        "studies",
        sa.Column("study_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('planned', 'active', 'complete', 'cancelled', 'invalid')",
            name="ck_study_status",
        ),
        sa.PrimaryKeyConstraint("study_id"),
        sa.UniqueConstraint("manifest_digest"),
        sa.UniqueConstraint("study_id", "version", name="uq_study_version"),
    )
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.create_index("ix_study_suite", ["suite_manifest_digest", "status"], unique=False)

    op.create_table(
        "verifier_results",
        sa.Column("result_id", sa.String(length=128), nullable=False),
        sa.Column("verifier_id", sa.String(length=128), nullable=False),
        sa.Column("verifier_version", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=192), nullable=False),
        sa.Column("disposition", sa.String(length=32), nullable=False),
        sa.Column("deterministic", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "disposition IN ('verified', 'rejected', 'unknown', 'infrastructure_failure')",
            name="ck_verifier_result_disposition",
        ),
        sa.PrimaryKeyConstraint("result_id"),
        sa.UniqueConstraint("record_digest"),
    )
    with op.batch_alter_table("verifier_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_verifier_scope", ["verifier_id", "scope", "created_at"], unique=False
        )

    op.create_table(
        "checkpoint_evaluations",
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("study_id", sa.String(length=128), nullable=False),
        sa.Column("suite_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"], ["checkpoints.checkpoint_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.study_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["suite_manifest_digest"], ["evaluation_suites.manifest_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("evaluation_id"),
        sa.UniqueConstraint(
            "checkpoint_id", "study_id", "suite_manifest_digest", name="uq_checkpoint_evaluation"
        ),
        sa.UniqueConstraint("record_digest"),
    )
    with op.batch_alter_table("checkpoint_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_checkpoint_evaluation_suite", ["suite_manifest_digest", "created_at"], unique=False
        )

    op.create_table(
        "rewards",
        sa.Column("reward_id", sa.String(length=128), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_digest", sa.String(length=71), nullable=False),
        sa.Column("input_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("derived_utility", sa.Float(), nullable=True),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id", "policy_version"],
            ["reward_policies.policy_id", "reward_policies.version"],
            name="fk_reward_policy",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("reward_id"),
        sa.UniqueConstraint("input_digest"),
        sa.UniqueConstraint("record_digest"),
    )
    with op.batch_alter_table("rewards", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reward_policy", ["policy_id", "policy_version", "created_at"], unique=False
        )

    op.create_table(
        "study_experiments",
        sa.Column("binding_id", sa.String(length=128), nullable=False),
        sa.Column("study_id", sa.String(length=128), nullable=False),
        sa.Column("experiment_id", sa.String(length=96), nullable=False),
        sa.Column("condition_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("research_role", sa.String(length=32), nullable=False),
        sa.Column("suite_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("environment_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("assignment_propensity", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "research_role IN ('target', 'baseline', 'teacher', 'verifier', 'adjudicator')",
            name="ck_study_experiment_role",
        ),
        sa.CheckConstraint(
            "assignment_propensity IS NULL OR (assignment_propensity > 0 AND assignment_propensity <= 1)",
            name="ck_study_experiment_propensity",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.experiment_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.study_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("study_id", "experiment_id", name="uq_study_experiment"),
    )
    op.create_table(
        "checkpoint_comparisons",
        sa.Column("comparison_id", sa.String(length=128), nullable=False),
        sa.Column("baseline_evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("suite_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("recommended", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "baseline_evaluation_id <> candidate_evaluation_id",
            name="ck_checkpoint_comparison_distinct",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_evaluation_id"],
            ["checkpoint_evaluations.evaluation_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_evaluation_id"],
            ["checkpoint_evaluations.evaluation_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "policy_version"],
            ["checkpoint_promotion_policies.policy_id", "checkpoint_promotion_policies.version"],
            name="fk_checkpoint_comparison_policy",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("comparison_id"),
        sa.UniqueConstraint(
            "baseline_evaluation_id",
            "candidate_evaluation_id",
            "policy_id",
            "policy_version",
            name="uq_checkpoint_comparison_inputs",
        ),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "training_eligibility_decisions",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("reward_id", sa.String(length=128), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reward_id"], ["rewards.reward_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("record_digest"),
    )
    with op.batch_alter_table("training_eligibility_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_training_eligibility_reward", ["reward_id", "created_at"], unique=False
        )

    op.create_table(
        "checkpoint_decisions",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("comparison_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=False),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('start_evaluation', 'promote', 'reject', 'quarantine', 'revoke')",
            name="ck_checkpoint_decision_action",
        ),
        sa.CheckConstraint(
            "from_status IN ('candidate', 'evaluating', 'promoted', 'rejected', 'quarantined', 'revoked')",
            name="ck_checkpoint_decision_from_status",
        ),
        sa.CheckConstraint(
            "to_status IN ('candidate', 'evaluating', 'promoted', 'rejected', 'quarantined', 'revoked')",
            name="ck_checkpoint_decision_to_status",
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"], ["checkpoints.checkpoint_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["comparison_id"], ["checkpoint_comparisons.comparison_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("record_digest"),
    )
    with op.batch_alter_table("checkpoint_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_checkpoint_decision", ["checkpoint_id", "created_at"], unique=False
        )

    op.create_table(
        "evaluation_trials",
        sa.Column("trial_id", sa.String(length=128), nullable=False),
        sa.Column("study_id", sa.String(length=128), nullable=False),
        sa.Column("trial_type", sa.String(length=32), nullable=False),
        sa.Column("source_episode_id", sa.String(length=96), nullable=False),
        sa.Column("interfering_episode_id", sa.String(length=96), nullable=True),
        sa.Column("student_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=256), nullable=False),
        sa.Column("state_snapshot_id", sa.String(length=96), nullable=False),
        sa.Column("competency_id", sa.String(length=128), nullable=False),
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("instance_group_id", sa.String(length=160), nullable=False),
        sa.Column("environment_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("assignment_seed", sa.Integer(), nullable=False),
        sa.Column("assignment_propensity", sa.Float(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("definition_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("outcome_json", sa.JSON(), nullable=True),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_token", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('scheduled', 'leased', 'complete', 'cancelled', 'invalid')",
            name="ck_evaluation_trial_status",
        ),
        sa.CheckConstraint(
            "trial_type IN ('retention', 'interference')", name="ck_evaluation_trial_type"
        ),
        sa.CheckConstraint(
            "assignment_propensity IS NULL OR (assignment_propensity > 0 AND assignment_propensity <= 1)",
            name="ck_evaluation_trial_propensity",
        ),
        sa.CheckConstraint(
            "(trial_type = 'retention' AND interfering_episode_id IS NULL) OR (trial_type = 'interference' AND interfering_episode_id IS NOT NULL)",
            name="ck_evaluation_trial_interfering_episode",
        ),
        sa.ForeignKeyConstraint(
            ["interfering_episode_id"], ["episodes.episode_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["corpus_items.item_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_episode_id"], ["episodes.episode_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["state_snapshot_id"], ["student_states.state_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.study_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("trial_id"),
        sa.UniqueConstraint("definition_digest"),
        sa.UniqueConstraint("lease_token"),
        sa.UniqueConstraint(
            "study_id",
            "student_id",
            "source_episode_id",
            "trial_type",
            "instance_group_id",
            name="uq_evaluation_trial_freshness",
        ),
    )
    with op.batch_alter_table("evaluation_trials", schema=None) as batch_op:
        batch_op.create_index(
            "ix_evaluation_trial_due", ["status", "due_at", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_evaluation_trial_student",
            ["student_id", "competency_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluation_trials", schema=None) as batch_op:
        batch_op.drop_index("ix_evaluation_trial_student")
        batch_op.drop_index("ix_evaluation_trial_due")

    op.drop_table("evaluation_trials")
    with op.batch_alter_table("checkpoint_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_checkpoint_decision")

    op.drop_table("checkpoint_decisions")
    with op.batch_alter_table("training_eligibility_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_training_eligibility_reward")

    op.drop_table("training_eligibility_decisions")
    op.drop_table("checkpoint_comparisons")
    op.drop_table("study_experiments")
    with op.batch_alter_table("rewards", schema=None) as batch_op:
        batch_op.drop_index("ix_reward_policy")

    op.drop_table("rewards")
    with op.batch_alter_table("checkpoint_evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_checkpoint_evaluation_suite")

    op.drop_table("checkpoint_evaluations")
    with op.batch_alter_table("verifier_results", schema=None) as batch_op:
        batch_op.drop_index("ix_verifier_scope")

    op.drop_table("verifier_results")
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.drop_index("ix_study_suite")

    op.drop_table("studies")
    op.drop_table("reward_policies")
    op.drop_table("evaluation_suites")
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.drop_index("ix_checkpoint_model_status")

    op.drop_table("checkpoints")
    op.drop_table("checkpoint_promotion_policies")
    # ### end Alembic commands ###
