"""add capability Atlas immutable registry

Revision ID: c9e8f4a1d2b3
Revises: a7c4e91d2b6f
Create Date: 2026-08-12
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9e8f4a1d2b3"
down_revision: str | Sequence[str] | None = "a7c4e91d2b6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_calls", sa.Column("result_envelope_digest", sa.String(length=71)))
    op.add_column("external_calls", sa.Column("result_model_id", sa.String(length=256)))
    op.add_column("external_calls", sa.Column("result_protocol", sa.String(length=128)))
    op.add_column("external_calls", sa.Column("result_raw_request_digest", sa.String(length=71)))
    op.add_column("external_calls", sa.Column("result_raw_response_digest", sa.String(length=71)))
    op.add_column("external_calls", sa.Column("result_output_text_digest", sa.String(length=71)))
    op.add_column("external_calls", sa.Column("result_usage", sa.JSON()))
    op.add_column("external_calls", sa.Column("result_capabilities_digest", sa.String(length=71)))
    op.add_column("external_calls", sa.Column("result_latency_ms", sa.Float()))
    op.create_table(
        "atlas_dataset_governance",
        sa.Column("governance_id", sa.String(length=192), nullable=False),
        sa.Column("benchmark_id", sa.String(length=192), nullable=False),
        sa.Column("benchmark_version", sa.String(length=128), nullable=False),
        sa.Column("dataset_revision", sa.String(length=192), nullable=False),
        sa.Column("access_classification", sa.String(length=32), nullable=False),
        sa.Column("redistribution_classification", sa.String(length=32), nullable=False),
        sa.Column("contamination_classification", sa.String(length=32), nullable=False),
        sa.Column("evaluation_class", sa.String(length=32), nullable=False),
        sa.Column("executable", sa.Boolean(), nullable=False),
        sa.Column("rights_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "access_classification IN ('local', 'registration_only', 'requires_approval', 'unavailable', 'legally_unclear')",
            name="ck_atlas_dataset_access",
        ),
        sa.CheckConstraint(
            "contamination_classification IN ('unassessed', 'no_known_exposure', 'suspected', 'confirmed')",
            name="ck_atlas_dataset_contamination",
        ),
        sa.CheckConstraint(
            "evaluation_class IN ('development', 'adaptive_search', 'challenge', 'sealed_promotion')",
            name="ck_atlas_dataset_evaluation_class",
        ),
        sa.CheckConstraint(
            "redistribution_classification IN ('permitted', 'metadata_only', 'prohibited', 'unknown')",
            name="ck_atlas_dataset_redistribution",
        ),
        sa.PrimaryKeyConstraint("governance_id"),
        sa.UniqueConstraint(
            "benchmark_id",
            "benchmark_version",
            "dataset_revision",
            name="uq_atlas_dataset_revision",
        ),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_dataset_benchmark",
        "atlas_dataset_governance",
        ["benchmark_id", "benchmark_version", "dataset_revision"],
        unique=False,
    )
    op.create_table(
        "atlas_items",
        sa.Column("item_digest", sa.String(length=71), nullable=False),
        sa.Column("item_id", sa.String(length=192), nullable=False),
        sa.Column("family_id", sa.String(length=192), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("adapter_kind", sa.String(length=48), nullable=False),
        sa.Column("prompt_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "adapter_kind IN ('static_qa', 'generated_verifier', 'coding_agentic', 'interactive_environment', 'context_memory', 'multimodal')",
            name="ck_atlas_item_adapter_kind",
        ),
        sa.PrimaryKeyConstraint("item_digest"),
        sa.UniqueConstraint("item_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_item_family", "atlas_items", ["family_id", "difficulty"], unique=False
    )
    op.create_table(
        "atlas_ontologies",
        sa.Column("ontology_digest", sa.String(length=71), nullable=False),
        sa.Column("ontology_id", sa.String(length=192), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ontology_digest"),
        sa.UniqueConstraint("ontology_id", "version", name="uq_atlas_ontology_version"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "atlas_benchmark_claims",
        sa.Column("claim_id", sa.String(length=192), nullable=False),
        sa.Column("supersedes_claim_id", sa.String(length=192), nullable=True),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_revision", sa.String(length=192), nullable=False),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("model_revision", sa.String(length=192), nullable=False),
        sa.Column("benchmark_id", sa.String(length=192), nullable=False),
        sa.Column("benchmark_version", sa.String(length=128), nullable=False),
        sa.Column("split", sa.String(length=128), nullable=False),
        sa.Column("metric_id", sa.String(length=192), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=96), nullable=True),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_kind IN ('vendor', 'upstream', 'community')",
            name="ck_atlas_benchmark_claim_source_kind",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_claim_id"], ["atlas_benchmark_claims.claim_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("claim_id"),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("supersedes_claim_id", name="uq_atlas_claim_supersession"),
    )
    op.create_index(
        "ix_atlas_claim_benchmark",
        "atlas_benchmark_claims",
        ["benchmark_id", "benchmark_version", "metric_id"],
        unique=False,
    )
    op.create_index(
        "ix_atlas_claim_model",
        "atlas_benchmark_claims",
        ["model_id", "model_revision"],
        unique=False,
    )
    op.create_table(
        "atlas_campaigns",
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("campaign_id", sa.String(length=192), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("ontology_digest", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned', 'ready', 'externally_gated', 'complete', 'invalid')",
            name="ck_atlas_campaign_status",
        ),
        sa.ForeignKeyConstraint(
            ["ontology_digest"], ["atlas_ontologies.ontology_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("campaign_digest"),
        sa.UniqueConstraint("campaign_id", "version", name="uq_atlas_campaign_version"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_campaign_status", "atlas_campaigns", ["status", "created_at"], unique=False
    )
    op.create_table(
        "atlas_exploratory_proposals",
        sa.Column("proposal_id", sa.String(length=192), nullable=False),
        sa.Column("deduplication_key", sa.String(length=71), nullable=False),
        sa.Column("consent_evidence_digest", sa.String(length=71), nullable=False),
        sa.Column("source_trace_digest", sa.String(length=71), nullable=False),
        sa.Column("source_trace_artifact_id", sa.String(length=96), nullable=False),
        sa.Column("raw_chat_promoted", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "raw_chat_promoted = false", name="ck_atlas_proposal_raw_chat_not_promoted"
        ),
        sa.ForeignKeyConstraint(
            ["source_trace_artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
        sa.UniqueConstraint("deduplication_key"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "atlas_phenomena",
        sa.Column("phenomenon_digest", sa.String(length=71), nullable=False),
        sa.Column("phenomenon_id", sa.String(length=192), nullable=False),
        sa.Column("ontology_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ontology_digest"], ["atlas_ontologies.ontology_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("phenomenon_digest"),
        sa.UniqueConstraint("phenomenon_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "atlas_suites",
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_id", sa.String(length=192), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("governance_id", sa.String(length=192), nullable=False),
        sa.Column("benchmark_id", sa.String(length=192), nullable=False),
        sa.Column("benchmark_version", sa.String(length=128), nullable=False),
        sa.Column("split", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evaluation_class", sa.String(length=32), nullable=False),
        sa.Column("adapter_kind", sa.String(length=48), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("evaluation_suite_manifest_digest", sa.String(length=71), nullable=True),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "adapter_kind IN ('static_qa', 'generated_verifier', 'coding_agentic', 'interactive_environment', 'context_memory', 'multimodal')",
            name="ck_atlas_suite_adapter_kind",
        ),
        sa.CheckConstraint(
            "evaluation_class IN ('development', 'adaptive_search', 'challenge', 'sealed_promotion')",
            name="ck_atlas_suite_evaluation_class",
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'ready', 'sealed', 'blocked', 'retired')",
            name="ck_atlas_suite_status",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_suite_manifest_digest"],
            ["evaluation_suites.manifest_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["governance_id"], ["atlas_dataset_governance.governance_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("suite_digest"),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("suite_id", "version", name="uq_atlas_suite_version"),
    )
    op.create_index(
        "ix_atlas_suite_benchmark",
        "atlas_suites",
        ["benchmark_id", "benchmark_version", "split"],
        unique=False,
    )
    op.create_index(
        "ix_atlas_suite_evaluation_suite",
        "atlas_suites",
        ["evaluation_suite_manifest_digest"],
        unique=False,
    )
    op.create_table(
        "atlas_campaign_claims",
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("claim_id", sa.String(length=192), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest"], ["atlas_campaigns.campaign_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["atlas_benchmark_claims.claim_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("campaign_digest", "claim_id"),
    )
    op.create_table(
        "atlas_campaign_suites",
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("evaluation_class", sa.String(length=32), nullable=False),
        sa.Column("planned_item_count", sa.Integer(), nullable=False),
        sa.Column("trials_per_item", sa.Integer(), nullable=False),
        sa.Column("adaptive", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "evaluation_class IN ('development', 'adaptive_search', 'challenge', 'sealed_promotion')",
            name="ck_atlas_campaign_suite_evaluation_class",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest"], ["atlas_campaigns.campaign_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["suite_digest"], ["atlas_suites.suite_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("campaign_digest", "suite_digest"),
    )
    op.create_table(
        "atlas_probe_sets",
        sa.Column("probe_set_digest", sa.String(length=71), nullable=False),
        sa.Column("probe_set_id", sa.String(length=192), nullable=False),
        sa.Column("phenomenon_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("outcome_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["phenomenon_digest"], ["atlas_phenomena.phenomenon_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["suite_digest"], ["atlas_suites.suite_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("probe_set_digest"),
        sa.UniqueConstraint("probe_set_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "atlas_suite_items",
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("item_digest", sa.String(length=71), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["item_digest"], ["atlas_items.item_digest"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["suite_digest"], ["atlas_suites.suite_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("suite_digest", "item_digest"),
        sa.UniqueConstraint("suite_digest", "position", name="uq_atlas_suite_item_position"),
    )
    op.create_table(
        "atlas_campaign_conditions",
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.Column("required_execution_digest", sa.String(length=71), nullable=True),
        sa.Column("externally_gated", sa.Boolean(), nullable=False),
        sa.Column("condition_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest"],
            ["atlas_campaigns.campaign_digest"],
            name="fk_atlas_campaign_condition_campaign",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["required_execution_digest"],
            ["research_executions.execution_digest"],
            name="fk_atlas_campaign_condition_execution",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("campaign_digest", "condition_id"),
    )
    op.create_table(
        "atlas_exploratory_reproductions",
        sa.Column("reproduction_id", sa.String(length=192), nullable=False),
        sa.Column("proposal_id", sa.String(length=192), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("independent_item_digest", sa.String(length=71), nullable=False),
        sa.Column("reproduced", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["independent_item_digest"], ["atlas_items.item_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["atlas_exploratory_proposals.proposal_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("reproduction_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_table(
        "atlas_failure_clusters",
        sa.Column("cluster_digest", sa.String(length=71), nullable=False),
        sa.Column("cluster_id", sa.String(length=192), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("ontology_digest", sa.String(length=71), nullable=False),
        sa.Column("probe_set_digest", sa.String(length=71), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('proposed', 'admitted', 'rejected', 'superseded')",
            name="ck_atlas_failure_cluster_status",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest"], ["atlas_campaigns.campaign_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ontology_digest"], ["atlas_ontologies.ontology_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["probe_set_digest"], ["atlas_probe_sets.probe_set_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("cluster_digest"),
        sa.UniqueConstraint("cluster_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_failure_cluster_campaign",
        "atlas_failure_clusters",
        ["campaign_digest", "status"],
        unique=False,
    )
    op.create_table(
        "atlas_probe_items",
        sa.Column("probe_set_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("item_digest", sa.String(length=71), nullable=False),
        sa.ForeignKeyConstraint(
            ["probe_set_digest"], ["atlas_probe_sets.probe_set_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["suite_digest", "item_digest"],
            ["atlas_suite_items.suite_digest", "atlas_suite_items.item_digest"],
            name="fk_atlas_probe_item_suite_item",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("probe_set_digest", "item_digest"),
    )
    op.create_table(
        "atlas_snapshots",
        sa.Column("snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("snapshot_id", sa.String(length=192), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("harness_profile_digest", sa.String(length=71), nullable=False),
        sa.Column("ontology_digest", sa.String(length=71), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("promotion_eligible", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest"], ["atlas_campaigns.campaign_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["harness_profile_digest"], ["harness_profiles.profile_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ontology_digest"], ["atlas_ontologies.ontology_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("snapshot_digest"),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("snapshot_id"),
    )
    op.create_index(
        "ix_atlas_snapshot_execution",
        "atlas_snapshots",
        ["research_execution_digest", "created_at"],
        unique=False,
    )
    op.create_table(
        "atlas_comparisons",
        sa.Column("comparison_digest", sa.String(length=71), nullable=False),
        sa.Column("comparison_id", sa.String(length=192), nullable=False),
        sa.Column("left_snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("right_snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("causal_claim_permitted", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "left_snapshot_digest <> right_snapshot_digest",
            name="ck_atlas_comparison_distinct_snapshots",
        ),
        sa.ForeignKeyConstraint(
            ["left_snapshot_digest"],
            ["atlas_snapshots.snapshot_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["right_snapshot_digest"],
            ["atlas_snapshots.snapshot_digest"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("comparison_digest"),
        sa.UniqueConstraint("comparison_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_comparison_snapshots",
        "atlas_comparisons",
        ["left_snapshot_digest", "right_snapshot_digest"],
        unique=False,
    )
    op.create_table(
        "atlas_allocations",
        sa.Column("allocation_id", sa.String(length=192), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("item_digest", sa.String(length=71), nullable=False),
        sa.Column("trial_index", sa.Integer(), nullable=False),
        sa.Column("decision_sequence", sa.Integer(), nullable=False),
        sa.Column("decision_evidence_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "condition_id"],
            ["atlas_campaign_conditions.campaign_digest", "atlas_campaign_conditions.condition_id"],
            name="fk_atlas_allocation_campaign_condition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "suite_digest"],
            ["atlas_campaign_suites.campaign_digest", "atlas_campaign_suites.suite_digest"],
            name="fk_atlas_allocation_campaign_suite",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suite_digest", "item_digest"],
            ["atlas_suite_items.suite_digest", "atlas_suite_items.item_digest"],
            name="fk_atlas_allocation_suite_item",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("allocation_id"),
        sa.UniqueConstraint(
            "campaign_digest",
            "condition_id",
            "suite_digest",
            "item_digest",
            "trial_index",
            name="uq_atlas_allocation_trial",
        ),
        sa.UniqueConstraint(
            "campaign_digest",
            "condition_id",
            "suite_digest",
            "decision_sequence",
            name="uq_atlas_allocation_decision_sequence",
        ),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_allocation_campaign",
        "atlas_allocations",
        ["campaign_digest", "condition_id"],
        unique=False,
    )
    op.create_table(
        "atlas_campaign_suite_conditions",
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "condition_id"],
            ["atlas_campaign_conditions.campaign_digest", "atlas_campaign_conditions.condition_id"],
            name="fk_atlas_campaign_suite_condition_condition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "suite_digest"],
            ["atlas_campaign_suites.campaign_digest", "atlas_campaign_suites.suite_digest"],
            name="fk_atlas_campaign_suite_condition_suite",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("campaign_digest", "suite_digest", "condition_id"),
    )
    op.create_table(
        "atlas_challenge_admissions",
        sa.Column("decision_id", sa.String(length=192), nullable=False),
        sa.Column("proposal_id", sa.String(length=192), nullable=False),
        sa.Column("reproduction_id", sa.String(length=192), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("challenge_suite_digest", sa.String(length=71), nullable=True),
        sa.Column("admitted_item_digest", sa.String(length=71), nullable=True),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("action IN ('admit', 'reject')", name="ck_atlas_challenge_action"),
        sa.ForeignKeyConstraint(
            ["challenge_suite_digest", "admitted_item_digest"],
            ["atlas_suite_items.suite_digest", "atlas_suite_items.item_digest"],
            name="fk_atlas_challenge_admission_suite_item",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["atlas_exploratory_proposals.proposal_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reproduction_id"],
            ["atlas_exploratory_reproductions.reproduction_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("reproduction_id", name="uq_atlas_challenge_reproduction_decision"),
    )
    op.create_table(
        "atlas_memory_eligibility",
        sa.Column("assessment_id", sa.String(length=192), nullable=False),
        sa.Column("failure_cluster_digest", sa.String(length=71), nullable=False),
        sa.Column("source_suite_digest", sa.String(length=71), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_cluster_digest"],
            ["atlas_failure_clusters.cluster_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_suite_digest"], ["atlas_suites.suite_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_memory_eligible",
        "atlas_memory_eligibility",
        ["eligible", "created_at"],
        unique=False,
    )
    op.create_table(
        "atlas_training_eligibility",
        sa.Column("assessment_id", sa.String(length=192), nullable=False),
        sa.Column("failure_cluster_digest", sa.String(length=71), nullable=False),
        sa.Column("source_suite_digest", sa.String(length=71), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_cluster_digest"],
            ["atlas_failure_clusters.cluster_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_suite_digest"], ["atlas_suites.suite_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
        sa.UniqueConstraint("record_digest"),
    )
    op.create_index(
        "ix_atlas_training_eligible",
        "atlas_training_eligibility",
        ["eligible", "created_at"],
        unique=False,
    )
    op.create_table(
        "atlas_campaign_execution_bindings",
        sa.Column("binding_digest", sa.String(length=71), nullable=False),
        sa.Column("binding_id", sa.String(length=192), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("harness_profile_digest", sa.String(length=71), nullable=False),
        sa.Column("external_authorization_ref", sa.String(length=512), nullable=True),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "suite_digest", "condition_id"],
            [
                "atlas_campaign_suite_conditions.campaign_digest",
                "atlas_campaign_suite_conditions.suite_digest",
                "atlas_campaign_suite_conditions.condition_id",
            ],
            name="fk_atlas_execution_binding_suite_condition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["harness_profile_digest"], ["harness_profiles.profile_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("binding_digest"),
        sa.UniqueConstraint("binding_id"),
        sa.UniqueConstraint(
            "campaign_digest",
            "condition_id",
            "research_execution_digest",
            name="uq_atlas_execution_binding_coordinates",
        ),
        sa.UniqueConstraint(
            "campaign_digest",
            "condition_id",
            "suite_digest",
            "research_execution_digest",
            name="uq_atlas_execution_binding_request_target",
        ),
    )
    op.create_index(
        "ix_atlas_execution_binding_execution",
        "atlas_campaign_execution_bindings",
        ["research_execution_digest", "harness_profile_digest"],
        unique=False,
    )
    op.create_table(
        "atlas_run_manifests",
        sa.Column("manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("run_manifest_id", sa.String(length=192), nullable=False),
        sa.Column("run_id", sa.String(length=96), nullable=False),
        sa.Column("run_kind", sa.String(length=32), nullable=False),
        sa.Column("binding_digest", sa.String(length=71), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("harness_profile_digest", sa.String(length=71), nullable=False),
        sa.Column("evaluation_class", sa.String(length=32), nullable=False),
        sa.Column("adaptive", sa.Boolean(), nullable=False),
        sa.Column("allocation_policy_id", sa.String(length=192), nullable=False),
        sa.Column("allocation_policy_version", sa.String(length=128), nullable=False),
        sa.Column("stop_rule_id", sa.String(length=192), nullable=True),
        sa.Column("request_template_digest", sa.String(length=71), nullable=True),
        sa.Column("planned_request_count", sa.Integer(), nullable=False),
        sa.Column("max_retry_requests", sa.Integer(), nullable=False),
        sa.Column("max_input_tokens", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("max_actions", sa.Integer(), nullable=False),
        sa.Column("max_cost_usd", sa.Float(), nullable=False),
        sa.Column("external_execution", sa.Boolean(), nullable=False),
        sa.Column("external_authorization_ref", sa.String(length=512), nullable=True),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evaluation_class IN ('development', 'adaptive_search', 'challenge', 'sealed_promotion')",
            name="ck_atlas_run_manifest_evaluation_class",
        ),
        sa.CheckConstraint(
            "run_kind IN ('offline_verification', 'model_evaluation', 'replay_grading')",
            name="ck_atlas_run_manifest_kind",
        ),
        sa.ForeignKeyConstraint(
            ["binding_digest"],
            ["atlas_campaign_execution_bindings.binding_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "condition_id", "suite_digest", "research_execution_digest"],
            [
                "atlas_campaign_execution_bindings.campaign_digest",
                "atlas_campaign_execution_bindings.condition_id",
                "atlas_campaign_execution_bindings.suite_digest",
                "atlas_campaign_execution_bindings.research_execution_digest",
            ],
            name="fk_atlas_run_manifest_execution_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["harness_profile_digest"], ["harness_profiles.profile_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("manifest_digest"),
        sa.UniqueConstraint("run_id"),
        sa.UniqueConstraint("run_manifest_id"),
    )
    op.create_index(
        "ix_atlas_run_manifest_campaign",
        "atlas_run_manifests",
        ["campaign_digest", "condition_id"],
        unique=False,
    )
    op.create_table(
        "atlas_trial_requests",
        sa.Column("request_id", sa.String(length=192), nullable=False),
        sa.Column("allocation_id", sa.String(length=192), nullable=False),
        sa.Column("parent_request_id", sa.String(length=192), nullable=True),
        sa.Column("run_id", sa.String(length=96), nullable=False),
        sa.Column("campaign_digest", sa.String(length=71), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("condition_id", sa.String(length=192), nullable=False),
        sa.Column("suite_digest", sa.String(length=71), nullable=False),
        sa.Column("item_digest", sa.String(length=71), nullable=False),
        sa.Column("trial_index", sa.Integer(), nullable=False),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column("request_digest", sa.String(length=71), nullable=False),
        sa.Column("prompt_digest", sa.String(length=71), nullable=False),
        sa.Column("tool_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("adapter_id", sa.String(length=192), nullable=False),
        sa.Column("adapter_version", sa.String(length=128), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["atlas_allocations.allocation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "condition_id", "suite_digest", "research_execution_digest"],
            [
                "atlas_campaign_execution_bindings.campaign_digest",
                "atlas_campaign_execution_bindings.condition_id",
                "atlas_campaign_execution_bindings.suite_digest",
                "atlas_campaign_execution_bindings.research_execution_digest",
            ],
            name="fk_atlas_trial_request_execution_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_digest", "condition_id"],
            ["atlas_campaign_conditions.campaign_digest", "atlas_campaign_conditions.condition_id"],
            name="fk_atlas_trial_request_campaign_condition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_request_id"], ["atlas_trial_requests.request_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["atlas_run_manifests.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["suite_digest", "item_digest"],
            ["atlas_suite_items.suite_digest", "atlas_suite_items.item_digest"],
            name="fk_atlas_trial_request_suite_item",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("request_id"),
        sa.UniqueConstraint("allocation_id", "attempt_index", name="uq_atlas_request_attempt"),
        sa.UniqueConstraint(
            "campaign_digest",
            "condition_id",
            "suite_digest",
            "item_digest",
            "trial_index",
            "attempt_index",
            name="uq_atlas_request_trial_attempt",
        ),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("request_digest"),
    )
    op.create_index(
        "ix_atlas_request_execution",
        "atlas_trial_requests",
        ["research_execution_digest", "created_at"],
        unique=False,
    )
    op.create_table(
        "atlas_trial_results",
        sa.Column("result_id", sa.String(length=192), nullable=False),
        sa.Column("request_id", sa.String(length=192), nullable=False),
        sa.Column("research_execution_digest", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("response_artifact_id", sa.String(length=96), nullable=True),
        sa.Column("result_digest", sa.String(length=71), nullable=False),
        sa.Column("record_digest", sa.String(length=71), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('verified_success', 'verified_failure', 'partial', 'abstained', 'malformed', 'unscorable', 'verifier_failure', 'parser_failure', 'timeout', 'infrastructure_failure', 'contaminated', 'not_run')",
            name="ck_atlas_trial_result_status",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["atlas_trial_requests.request_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["research_execution_digest"],
            ["research_executions.execution_digest"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["response_artifact_id"], ["artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("result_id"),
        sa.UniqueConstraint("record_digest"),
        sa.UniqueConstraint("request_id"),
        sa.UniqueConstraint("result_digest"),
    )
    op.create_index(
        "ix_atlas_result_execution",
        "atlas_trial_results",
        ["research_execution_digest", "completed_at"],
        unique=False,
    )
    op.create_table(
        "atlas_exploratory_reproduction_results",
        sa.Column("reproduction_id", sa.String(length=192), nullable=False),
        sa.Column("result_digest", sa.String(length=71), nullable=False),
        sa.ForeignKeyConstraint(
            ["reproduction_id"],
            ["atlas_exploratory_reproductions.reproduction_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_digest"], ["atlas_trial_results.result_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("reproduction_id", "result_digest"),
    )
    op.create_table(
        "atlas_failure_cluster_results",
        sa.Column("cluster_digest", sa.String(length=71), nullable=False),
        sa.Column("result_digest", sa.String(length=71), nullable=False),
        sa.Column("exemplar", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_digest"], ["atlas_failure_clusters.cluster_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["result_digest"], ["atlas_trial_results.result_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("cluster_digest", "result_digest"),
    )
    op.create_table(
        "atlas_probe_results",
        sa.Column("probe_set_digest", sa.String(length=71), nullable=False),
        sa.Column("result_digest", sa.String(length=71), nullable=False),
        sa.ForeignKeyConstraint(
            ["probe_set_digest"], ["atlas_probe_sets.probe_set_digest"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["result_digest"], ["atlas_trial_results.result_digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("probe_set_digest", "result_digest"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("atlas_probe_results")
    op.drop_table("atlas_failure_cluster_results")
    op.drop_table("atlas_exploratory_reproduction_results")
    op.drop_index("ix_atlas_result_execution", table_name="atlas_trial_results")
    op.drop_table("atlas_trial_results")
    op.drop_index("ix_atlas_request_execution", table_name="atlas_trial_requests")
    op.drop_table("atlas_trial_requests")
    op.drop_index("ix_atlas_run_manifest_campaign", table_name="atlas_run_manifests")
    op.drop_table("atlas_run_manifests")
    op.drop_index(
        "ix_atlas_execution_binding_execution", table_name="atlas_campaign_execution_bindings"
    )
    op.drop_table("atlas_campaign_execution_bindings")
    op.drop_index("ix_atlas_training_eligible", table_name="atlas_training_eligibility")
    op.drop_table("atlas_training_eligibility")
    op.drop_index("ix_atlas_memory_eligible", table_name="atlas_memory_eligibility")
    op.drop_table("atlas_memory_eligibility")
    op.drop_table("atlas_challenge_admissions")
    op.drop_table("atlas_campaign_suite_conditions")
    op.drop_index("ix_atlas_allocation_campaign", table_name="atlas_allocations")
    op.drop_table("atlas_allocations")
    op.drop_index("ix_atlas_comparison_snapshots", table_name="atlas_comparisons")
    op.drop_table("atlas_comparisons")
    op.drop_index("ix_atlas_snapshot_execution", table_name="atlas_snapshots")
    op.drop_table("atlas_snapshots")
    op.drop_table("atlas_probe_items")
    op.drop_index("ix_atlas_failure_cluster_campaign", table_name="atlas_failure_clusters")
    op.drop_table("atlas_failure_clusters")
    op.drop_table("atlas_exploratory_reproductions")
    op.drop_table("atlas_campaign_conditions")
    op.drop_table("atlas_suite_items")
    op.drop_table("atlas_probe_sets")
    op.drop_table("atlas_campaign_suites")
    op.drop_table("atlas_campaign_claims")
    op.drop_index("ix_atlas_suite_evaluation_suite", table_name="atlas_suites")
    op.drop_index("ix_atlas_suite_benchmark", table_name="atlas_suites")
    op.drop_table("atlas_suites")
    op.drop_table("atlas_phenomena")
    op.drop_table("atlas_exploratory_proposals")
    op.drop_index("ix_atlas_campaign_status", table_name="atlas_campaigns")
    op.drop_table("atlas_campaigns")
    op.drop_index("ix_atlas_claim_model", table_name="atlas_benchmark_claims")
    op.drop_index("ix_atlas_claim_benchmark", table_name="atlas_benchmark_claims")
    op.drop_table("atlas_benchmark_claims")
    op.drop_table("atlas_ontologies")
    op.drop_index("ix_atlas_item_family", table_name="atlas_items")
    op.drop_table("atlas_items")
    op.drop_index("ix_atlas_dataset_benchmark", table_name="atlas_dataset_governance")
    op.drop_table("atlas_dataset_governance")
    op.drop_column("external_calls", "result_latency_ms")
    op.drop_column("external_calls", "result_capabilities_digest")
    op.drop_column("external_calls", "result_usage")
    op.drop_column("external_calls", "result_output_text_digest")
    op.drop_column("external_calls", "result_raw_response_digest")
    op.drop_column("external_calls", "result_raw_request_digest")
    op.drop_column("external_calls", "result_protocol")
    op.drop_column("external_calls", "result_model_id")
    op.drop_column("external_calls", "result_envelope_digest")
    # ### end Alembic commands ###
